import About from '@/components/about'
import Contact from '@/components/contact'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Main from '@/components/main'
import Navbar from '@/components/navbar'
import Services from '@/components/services'
import Skills from '@/components/skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joseph Maguguli | my Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* navbar */}

      <Navbar/>

      {/* main */}

      <Main/>
      
      {/* about */}
      
      <About/>
      
      {/* skills */}

      <Skills/>

      {/* services */}

      <Services/>

      {/* contacts */}
      
      <Contact/>

      

    </div>
  )
}
